### ISSUE TITLE
Manage simple commands

### ISSUE THREAD

**Issue by Jsarda42** [eleaunord/minishell-jsarda-x-eleroty#11]
For the exec part need to manage the simple commands

**Comment by Jsarda42** [comment]
# Creating a Child Process with fork()
       - Use fork() to create a new process.
        - fork() returns a process ID (PID). The PID is 0 for the child process, and for the parent process, it is the child's PID.

    # Replacing the Process Image with execve()
        - Use execve() in the child process to replace the process image with the specified command.
        - execve() takes three arguments: the path to the executable, an array of arguments, and an array of environment variables.

    # Waiting for the Child Process to Finish with waitpid()
        - Use waitpid() in the parent process to wait for the child process to finish.
        - waitpid() takes the child process's PID and a pointer to an integer where the exit status will be stored.

    # Error Handling
       - Handle possible errors for fork(), execve(), and waitpid() using perror() and appropriate return codes.

**Comment by eleaunord** [comment]
https://pubs.opengroup.org/onlinepubs/009604499/utilities/xcu_chap02.html#tag_02_09_01
